# Site settings
title: "KropyvnytskyiJS &middot; Конференция для JS разработчиков в Кропивницком"
description: "KropyvnytskyiJS - это конференция для JavaScript и NodeJS разработчиков в Кропивницком"
keywords: "Кропивницкий, KropyvnytskyiJS, Kropyvnytskyi, Кировоград, Kirovohrad, NodeJS, NodeSchool, JavaScript, KirovohradJS, KrJS"
baseurl: ""
url: "http://kropjs.com"

# Build settings
markdown: kramdown
